### ISSUE TITLE
How to generate sha256 pin from a .crt file

### ISSUE THREAD

**Issue by abdulaziz733** [scottyab/ssl-pin-generator#1]
how to generate 2 sha256 pin certificate from file .crt we get from server?

try to run 
java -jar generatePins.jar filename.crt sha-256

ang getting error
The generated pinset are base-64 encoded hashes (default SHA-1, but supports SHA-256). Note: only run this on a trusted network.

Usage: "java -jar generatePins.jar <host>[:port] hashAlgorthm" i.e scottyab.com:443 sha-256 

Whoops something went wrong: filename.crt
java.net.UnknownHostException: filename.crt
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:426)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at com.scottyab.ssl.util.SSLPinGenerator.fetchAndPrintPinHashs(SSLPinGenerator.java:113)
	at com.scottyab.ssl.util.SSLPinGenerator.main(SSLPinGenerator.java:84)
	
the expected
Generating SSL pins for: scottyab.com
sha256/29pz6zLLFb2xdHtgFZQC8cRNrpLKxxxxxxxxxxxx
sha256/jQJTbIh0grw0/1TkHSumWb+Fs0Gxxxxxxxxxxxxx

**Comment by scottyab** [comment]
Hi, thanks for the question. ssl-pin-generator was built to accept url. it make HTTPS request and generates the SSL pins from the certs it downloads as part of the requst. If you have the .crt file you'll need to use `openssl` tool to extract the keys. See this [SO answer](https://stackoverflow.com/questions/36163093/how-do-we-generate-a-base64-encoded-sha256-hash-of-subjectpublickeyinfo-of-an-x#answer-36186060) it should help. 

`openssl x509 -in cert.crt -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64` (from the linked SO answer)

**Comment by abdulaziz733** [comment]
Thank you for answer
